name: Increment Version
on:
  workflow_dispatch:
    inputs:
      versionIncrementType:
        description: 'The type of increment'
        type: choice
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Increment Version
      run: ./gradlew incrementVersion --versionIncrementType=${{ github.event.inputs.versionIncrementType }} --versionIncrementBranch=master
      env:
        gitUserEmail: ${{ secrets.GIT_USER_EMAIL }}
        gitUserName: ${{ secrets.GIT_USER_NAME }}

    - name: Build with gradle
      run: gradle publish